# Generated by Django 4.2.3 on 2024-04-13 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('singlepage', '0002_user_total_matches'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_online',
            field=models.BooleanField(default=False),
        ),
    ]
