# Generated by Django 4.2.3 on 2024-04-16 14:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('singlepage', '0004_game_players_uid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='players_uid',
        ),
    ]
