# Generated by Django 4.2.3 on 2024-04-16 14:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('singlepage', '0005_remove_game_players_uid'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='player_uid',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='player', to=settings.AUTH_USER_MODEL),
        ),
    ]
