# Generated by Django 4.2.3 on 2024-04-18 11:31

from django.conf import settings
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('singlepage', '0006_game_player_uid'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tournament',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username_virtual_player', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=100), blank=True, default=list, size=None)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('state', models.BooleanField(default=False)),
                ('number_of_players', models.IntegerField(blank=True, default=0)),
                ('number_of_rounds', models.IntegerField(blank=True, default=0)),
                ('current_round', models.IntegerField(blank=True, default=0)),
                ('current_match', models.IntegerField(blank=True, default=0)),
                ('current_player', models.IntegerField(blank=True, default=0)),
                ('current_virtual_player', models.IntegerField(blank=True, default=0)),
                ('owner_uid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owner', to=settings.AUTH_USER_MODEL)),
                ('winner_uid', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tournament_winner', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
