# Generated by Django 4.2.3 on 2024-04-19 16:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('singlepage', '0007_tournament'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tournament',
            name='current_match',
        ),
        migrations.RemoveField(
            model_name='tournament',
            name='current_player',
        ),
        migrations.RemoveField(
            model_name='tournament',
            name='current_round',
        ),
        migrations.RemoveField(
            model_name='tournament',
            name='current_virtual_player',
        ),
    ]
