global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'django'
    static_configs:
      - targets: ['django:8000']

  - job_name : 'prometheus'
    static_configs:
      - targets: ['prometheus:9090']